language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
    - pypy
install:
  - pip install --upgrade pip
  - pip install coveralls
  - pip install tox
script:
  coverage run --source=untangle ./setup.py test

after_success:
  coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4e8e4267eec52e11a384
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
